# Generated by Django 2.1.7 on 2019-03-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OldCapacityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkedcars', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('actualparkedcars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('parkinglot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartP.ParkingLot')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartP.Country')),
            ],
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartP.Town'),
        ),
        migrations.AddField(
            model_name='oldcapacitydata',
            name='parkinglot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartP.ParkingLot'),
        ),
        migrations.AddField(
            model_name='favouriteparkinglot',
            name='parkinglot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartP.ParkingLot'),
        ),
        migrations.AddField(
            model_name='favouriteparkinglot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartP.User'),
        ),
    ]
