# Generated by Django 2.1.7 on 2019-04-12 20:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartP', '0004_auto_20190330_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
